### ISSUE TITLE
Spotify stopped playing songs

### ISSUE THREAD

**Issue by tejxv** [Sakurai07/SpotifyAdblocker#1]
well, after injecting the script spotify just refuses to play songs
and is there any way i can uninstall the script?

Spotify v1.1.54.592.gc0b20638
Windows 10 v20H2

**Comment by wynwxst** [comment]
uhh it's meant for windows 7/8 @tejxv

**Comment by tejxv** [comment]
bruh
ok

**Comment by wynwxst** [comment]
@tejxv to uninstall all u need to do is
1. go to %systemroot%/system32/etc/hosts/
2. open hosts with whatever text editor
3. delete the spotify ad block part

**Comment by wynwxst** [comment]
@tejxv for the windows 10 version it's https://github.com/Kaneki07/SpotifyFree

**Comment by tejxv** [comment]
> @tejxv to uninstall all u need to do is
> 
> 1. go to %systemroot%/system32/etc/hosts/
> 2. open hosts with whatever text editor
> 3. delete the spotify ad block part

yeah i just did that and it's working fine now
and thanks for that, i'll check it out!

**Comment by wynwxst** [comment]
np
